I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/labels/000-TempDefs.rpy", line 2, in script
    image d 1a = im.Composite((371, 1004), (0, 240), "chars/d1.png" (100, 400), "chars/da.png")
  File "game/labels/000-TempDefs.rpy", line 2, in <module>
    image d 1a = im.Composite((371, 1004), (0, 240), "chars/d1.png" (100, 400), "chars/da.png")
TypeError: 'unicode' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/labels/000-TempDefs.rpy", line 2, in script
    image d 1a = im.Composite((371, 1004), (0, 240), "chars/d1.png" (100, 400), "chars/da.png")
  File "C:\Users\John Dough\Documents\renpy-7.3.5-sdk.7z\renpy-7.3.5-sdk\renpy\ast.py", line 1013, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\John Dough\Documents\renpy-7.3.5-sdk.7z\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/labels/000-TempDefs.rpy", line 2, in <module>
    image d 1a = im.Composite((371, 1004), (0, 240), "chars/d1.png" (100, 400), "chars/da.png")
TypeError: 'unicode' object is not callable

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Ganymead 1.0
Wed Jun 10 17:00:07 2020
