I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/labels/cassDate1.rpy", line 925, in script
    
  File "game/labels/cassDate1.rpy", line 925, in <module>
    
NameError: name 'kissZoom12' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/labels/cassDate1.rpy", line 925, in script
    
  File "C:\Users\John Dough\Documents\renpy-7.3.5-sdk.7z\renpy-7.3.5-sdk\renpy\ast.py", line 1183, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\John Dough\Documents\renpy-7.3.5-sdk.7z\renpy-7.3.5-sdk\renpy\ast.py", line 1142, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\John Dough\Documents\renpy-7.3.5-sdk.7z\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\John Dough\Documents\renpy-7.3.5-sdk.7z\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/labels/cassDate1.rpy", line 925, in <module>
    
NameError: name 'kissZoom12' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Intolerable Jewelry 1.0
Sat Jun 20 23:40:53 2020
