I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/labels/Second route/fontCommon1.rpy", line 500, in script call
    call fontRoute21 from _call_fontRoute21
  File "game/labels/Second route/fontRoute21.rpy", line 399, in script
    show image flipBook2 with dissolve
  File "game/labels/Second route/fontRoute21.rpy", line 399, in <module>
    show image flipBook2 with dissolve
NameError: name 'flipBook2' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/labels/Second route/fontCommon1.rpy", line 500, in script call
    call fontRoute21 from _call_fontRoute21
  File "game/labels/Second route/fontRoute21.rpy", line 399, in script
    show image flipBook2 with dissolve
  File "C:\Users\John Dough\Documents\renpy-7.3.5-sdk.7z\renpy-7.3.5-sdk\renpy\ast.py", line 1183, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\John Dough\Documents\renpy-7.3.5-sdk.7z\renpy-7.3.5-sdk\renpy\ast.py", line 1139, in show_imspec
    expression = renpy.python.py_eval(expression)
  File "C:\Users\John Dough\Documents\renpy-7.3.5-sdk.7z\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\John Dough\Documents\renpy-7.3.5-sdk.7z\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/labels/Second route/fontRoute21.rpy", line 399, in <module>
    show image flipBook2 with dissolve
NameError: name 'flipBook2' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Intolerable Jewelry 0.6
Mon Sep 14 00:31:56 2020
